import { CommonModule } from '@angular/common';
import { Component } from '@angular/core';
import { HeaderComponent } from '../header/header.component';

@Component({
  selector: 'app-all-customer',
  standalone: true,
  imports: [CommonModule, HeaderComponent],
  templateUrl: './all-customer.component.html',
  styleUrl: './all-customer.component.scss',
})
export class AllCustomer {
  customers = [
    {
      name: 'Amit Sharma',
      phone: '9876543210',
      address: '123 Main St, Delhi',
      status: 'Confirm',
      totalAmount: 1200,
      recievedAmount: 1200,
      paymentType: 'Cash',
      invoice: 'INV001',
    },
    {
      name: 'Priya Singh',
      phone: '9876501234',
      address: '56 Market Rd, Mumbai',
      status: 'InProgress',
      totalAmount: 850,
      recievedAmount: 500,
      paymentType: 'Card',
      invoice: 'INV002',
    },
    {
      name: 'Rahul Gupta',
      phone: '9876534432',
      address: '89 Sector 4, Noida',
      status: 'Completed',
      totalAmount: 2100,
      recievedAmount: 2100,
      paymentType: 'UPI',
      invoice: 'INV003',
    },
    {
      name: 'Amit Sharma',
      phone: '9876543210',
      address: '123 Main St, Delhi',
      status: 'Confirm',
      totalAmount: 1200,
      recievedAmount: 1200,
      paymentType: 'Cash',
      invoice: 'INV001',
    },
    {
      name: 'Priya Singh',
      phone: '9876501234',
      address: '56 Market Rd, Mumbai',
      status: 'InProgress',
      totalAmount: 850,
      recievedAmount: 500,
      paymentType: 'Card',
      invoice: 'INV002',
    },
    {
      name: 'Rahul Gupta',
      phone: '9876534432',
      address: '89 Sector 4, Noida',
      status: 'Completed',
      totalAmount: 2100,
      recievedAmount: 2100,
      paymentType: 'UPI',
      invoice: 'INV003',
    },
    {
      name: 'Amit Sharma',
      phone: '9876543210',
      address: '123 Main St, Delhi',
      status: 'Confirm',
      totalAmount: 1200,
      recievedAmount: 1200,
      paymentType: 'Cash',
      invoice: 'INV001',
    },
    {
      name: 'Priya Singh',
      phone: '9876501234',
      address: '56 Market Rd, Mumbai',
      status: 'InProgress',
      totalAmount: 850,
      recievedAmount: 500,
      paymentType: 'Card',
      invoice: 'INV002',
    },
    {
      name: 'Rahul Gupta',
      phone: '9876534432',
      address: '89 Sector 4, Noida',
      status: 'Completed',
      totalAmount: 2100,
      recievedAmount: 2100,
      paymentType: 'UPI',
      invoice: 'INV003',
    },
    {
      name: 'Amit Sharma',
      phone: '9876543210',
      address: '123 Main St, Delhi',
      status: 'Confirm',
      totalAmount: 1200,
      recievedAmount: 1200,
      paymentType: 'Cash',
      invoice: 'INV001',
    },
    {
      name: 'Priya Singh',
      phone: '9876501234',
      address: '56 Market Rd, Mumbai',
      status: 'InProgress',
      totalAmount: 850,
      recievedAmount: 500,
      paymentType: 'Card',
      invoice: 'INV002',
    },
    {
      name: 'Rahul Gupta',
      phone: '9876534432',
      address: '89 Sector 4, Noida',
      status: 'Completed',
      totalAmount: 2100,
      recievedAmount: 2100,
      paymentType: 'UPI',
      invoice: 'INV003',
    },
    {
      name: 'Amit Sharma',
      phone: '9876543210',
      address: '123 Main St, Delhi',
      status: 'Confirm',
      totalAmount: 1200,
      recievedAmount: 1200,
      paymentType: 'Cash',
      invoice: 'INV001',
    },
    {
      name: 'Priya Singh',
      phone: '9876501234',
      address: '56 Market Rd, Mumbai',
      status: 'InProgress',
      totalAmount: 850,
      recievedAmount: 500,
      paymentType: 'Card',
      invoice: 'INV002',
    },
    {
      name: 'Rahul Gupta',
      phone: '9876534432',
      address: '89 Sector 4, Noida',
      status: 'Completed',
      totalAmount: 2100,
      recievedAmount: 2100,
      paymentType: 'UPI',
      invoice: 'INV003',
    },
  ];
}
